syntax on                 " enable syntax highlighting
set list                  " display hidden characters, like <TAB>
filetype plugin indent on " enables the filetype plugin for indentation

set expandtab     " insert spaces instead of <TAB>
set autoindent    " copy indentation level from previous line
set copyindent    " copy the structure of the existing lines indent"
set number        " enable line numbers
set shiftwidth=2  " number of spaces to auto-indent with >>
set softtabstop=2 " number of spaces in <TAB>
